Upload files
kifion/GuessTheNumberFlutterDemo pull request #1
Opened 2020-11-05 07:20 UTC by kifion

2020-11-05 08:58 UTC, vasilevkin commented on lib/main.dart
> +class GuessNumberApp extends StatefulWidget {
move to separate file app.dart

2020-11-05 08:59 UTC, vasilevkin commented on lib/main.dart
> +          data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
use constant instead of magic numbers

2020-11-05 08:59 UTC, vasilevkin commented on lib/main.dart
> +      title: 'Guess the number',
should be localizable

2020-11-05 09:01 UTC, vasilevkin commented on lib/screens/home.dart
> +class IconSettingsWidget extends StatelessWidget {
move to separate file

2020-11-05 09:02 UTC, vasilevkin requested changes
request changes

2020-11-05 13:07 UTC, vasilevkin commented on lib/localization/locale_constant.dart
> +import 'dart:ui';
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The method '_greaterThanFromInteger' was called on null.
Receiver: null
Tried calling: _greaterThanFromInteger(1)

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      int.> (dart:core-patch/integers.dart:105:18)
#2      HomeState._onButtonPressed (package:RandomNumber/screens/home.dart:32:28)
#3      HomeState.build.<anonymous closure> (package:RandomNumber/screens/home.dart:82:42)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
#9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:219:7)
#10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:477:9)
#11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:78:12)
#12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:124:9)
#13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:122:18)
#15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:108:7)
#16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:220:19)
#17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
#18     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
#19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
#20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
#24     _invoke1 (dart:ui/hooks.dart:267:10)
#25     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
(elided 3 frames from dart:async)

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#38267
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The method '_greaterThanFromInteger' was called on null.
Receiver: null
Tried calling: _greaterThanFromInteger(1)
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: NoSuchMethodError: The method '_greaterThanFromInteger' was called on null.

2020-11-05 13:08 UTC, vasilevkin commented on lib/localization/locale_constant.dart
> +import 'package:flutter/material.dart';
check localization when the app is installed from scratch

2020-11-06 11:57 UTC, vasilevkin commented
use snake_case_notation for package/files/project names

2020-11-10 12:17 UTC, kifion commented on lib/localization/locale_constant.dart
> +import 'dart:ui';
import was deleted

2020-11-10 14:09 UTC, kifion commented on lib/localization/locale_constant.dart
> +import 'package:flutter/material.dart';
removed dar ui.

2020-11-10 14:09 UTC, merged